### Variaveis ###
@base = https://api.paramour.com.br/v1
@storePublicId = bling-fdgwsdfgsgdfsgfdwre

#### [X] Login ####
POST {{base}}/login
Content-Type: application/json

{
    "email": "maxsouza150@hotmail.com",
    "pass": "Password@1"
}

#### [X] Listar Lojas ####
GET {{base}}/store/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Cadastrar Lojas ####
POST {{base}}/store/register?debug=true
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId": "loja-do-mineiro",
    "name": "Loja do Mineiro",
    "email": "mineiro@gmail.com",
    "asaasApiKey": "dsiqmkaosmdaopieu4m423423",
    "blingApiKey": "dsiqmkaosmdaopieu4m423423"
}

#### [X] Atualizar Lojas ####
POST {{base}}/store/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "fea268a9-12c0-45be-8280-604eb32d8ecb",
    "externalId": "loja-do-mineiro2",
    "name": "Loja do Mineiro2",
    "email": "mineiro2@gmail.com",
    "asaasApiKey": "dsiqmkaosmdaopieu4m42342344",
    "blingApiKey": "dsiqmkaosmdaopieu4m42342355"
}

#### [X] status Lojas ####
POST {{base}}/store/status
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "fea268a9-12c0-45be-8280-604eb32d8ecb",
    "status": "ACTIVE"
}

#### [X] Deletar Lojas ####
POST {{base}}/store/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "fea268a9-12c0-45be-8280-604eb32d8ecb"
}

#### [X] Criar Usuarios ####
POST {{base}}/user/create
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "name": "admin_user",
    "email": "admin_user@gmail.com",
    "pass": "Password@1",
    "phone": "123123"
}

#### [X] Listar Usuarios ####
GET {{base}}/user/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Editar Usuarios ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "836e9bd8-8714-4533-b1be-1a478c1a90b3",
    "name": "admin_user_2",
    "phone": "82 99621-0022",
    "status": "ACTIVE"
}

#### [X] Atualizar Senha de Usuarios ####
POST {{base}}/user/update/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "836e9bd8-8714-4533-b1be-1a478c1a90b3",
    "pass": "Password@12"
}

#### [X] Alterar dados do Usuario ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "836e9bd8-8714-4533-b1be-1a478c1a90b3",
    "name": "Max Edit",
    "phone": "82 99621-1554",
    "status": "ACTIVE"
}

#### [X] Deletar Usuarios ####
POST {{base}}/user/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "836e9bd8-8714-4533-b1be-1a478c1a90b3"
}

#### [ ] Criar Webhook ####
POST {{base}}/webhook/create/{{storePublicId}}
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "id": 42
}

#### [X] Listar Webhook ####
GET {{base}}/webhook/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh


#### [ ] Recuparar senha ####
POST {{base}}/recover/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "br.rafael@outlook.com"
}

#### [ ] Alter Pass ####
POST {{base}}/alter/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "br.rafael@outlook.com",
    "code" : "AS56DA41SDA64D44AD",
    "pass" : "123456",
}
