### Variaveis ###
@base = https://api.paramour.com.br/v1
@storePublicId = bling-fdgwsdfgsgdfsgfdwre

#### [X] Login ####
POST {{base}}/login
Content-Type: application/json

{
    "email": "maxsouza150@hotmail.com",
    "pass": "Password@1"
}

#### [X] Listar Lojas ####
GET {{base}}/store/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar Informações da Lojas ####
GET {{base}}/store/info?publicId=a33c7aee-3738-4ab2-9947-c3e7764dd40d
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Cadastrar Lojas ####
POST {{base}}/store/register?debug=true
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId": "loja-do-alagoano",
    "name": "Loja do Alagoano",
    "email": "alagoano@gmail.com",
    "asaasApiKey": "0",
    "blingClientId": "1",
    "blingClientSecret": "2"
}

#### [X] Atualizar Lojas ####
POST {{base}}/store/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99",
    "externalId": "loja-do-alagoano1",
    "name": "Loja do Alagoano1",
    "email": "alagoano1@gmail.com",
    "asaasApiKey": "0",
    "blingClientId": "1",
    "blingClientSecret": "2"
}

#### [X] status Lojas ####
POST {{base}}/store/status
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99",
    "status": "INACTIVE"
}

#### [X] Deletar Lojas ####
POST {{base}}/store/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99"
}

#### [X] Criar Usuarios ####
POST {{base}}/user/create
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "name": "Max",
    "email": "maximizebot@gmail.com",
    "pass": "Password@1",
    "phone": "123123"
}

#### [X] Listar Usuarios ####
GET {{base}}/user/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar informações do usuario ####
GET {{base}}/user/info?publicId=e58af946-0426-4629-831f-027b59a443d9
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Editar Usuarios ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "name": "admin_user_full2",
    "phone": "82 99621-0022",
    "status": "ACTIVE"
}

#### [X] Atualizar Senha de Usuarios ####
POST {{base}}/user/update/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "pass": "Password@12"
}

#### [X] Alterar dados do Usuario ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "name": "admin_user_edit",
    "phone": "82 99621-1554",
    "status": "ACTIVE"
}

#### [X] Deletar Usuarios ####
POST {{base}}/user/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9"
}

#### [ ] Criar Webhook ####
POST {{base}}/webhook/create/bling-loja-do-alagoano?debug=true
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

data={
    "retorno": {
        "pedidos": [
            {
                "pedido": {
                    "desconto": "0,00",
                    "observacoes": "",
                    "observacaointerna": "",
                    "data": "2024-08-29",
                    "numero": "212",
                    "numeroOrdemCompra": "",
                    "vendedor": "",
                    "valorfrete": "0.00",
                    "outrasdespesas": "0.00",
                    "totalprodutos": "264.90",
                    "totalvenda": "264.90",
                    "situacao": "Atendido",
                    "dataSaida": "2024-08-29",
                    "cliente": {
                        "id": "16923756638",
                        "nome": "Teste Asaas",
                        "cnpj": "85260731093",
                        "ie": "",
                        "indIEDest": "9",
                        "rg": "",
                        "endereco": "Rua Graciliano Ramos",
                        "numero": "536",
                        "complemento": "",
                        "cidade": "Arapiraca",
                        "bairro": "Baix\u00e3o",
                        "cep": "57305365",
                        "uf": "AL",
                        "email": "maxsouza150@hotmail.com",
                        "celular": "(82) 99621-1554",
                        "fone": ""
                    },
                    "transporte": {
                        "tipo_frete": "R",
                        "qtde_volumes": "0",
                        "peso_bruto": "0.000"
                    },
                    "itens": [
                        {
                            "item": {
                                "codigo": "AN35625-16",
                                "descricao": "ANEL COM 4 AROS ENTRELA\u00c7ADOS  DOIS LISOS DOIS CRAVEJADOS TAMANHO:16",
                                "quantidade": "1.0000",
                                "valorunidade": "264.9000000000",
                                "precocusto": "35.2800000000",
                                "descontoItem": "0.00",
                                "un": "P\u00c7",
                                "pesoBruto": "0.02000",
                                "largura": "10",
                                "altura": "0",
                                "profundidade": "4",
                                "descricaoDetalhada": "",
                                "unidadeMedida": "cm",
                                "gtin": ""
                            }
                        }
                    ],
                    "parcelas": [
                        {
                            "parcela": {
                                "idLancamento": "21013846458",
                                "valor": "300.45",
                                "dataVencimento": "2024-09-03",
                                "obs": "",
                                "destino": "1",
                                "forma_pagamento": {
                                    "id": "2779137",
                                    "descricao": "BOLETO BRADESCO",
                                    "codigoFiscal": "15"
                                }
                            }
                        },
                        {
                            "parcela": {
                                "idLancamento": "21013846458",
                                "valor": "200.45",
                                "dataVencimento": "2024-09-03",
                                "obs": "",
                                "destino": "1",
                                "forma_pagamento": {
                                    "id": "2779137",
                                    "descricao": "BOLETO BRADESCO",
                                    "codigoFiscal": "15"
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
}

#### [X] Listar Boletos ####
GET {{base}}/payment/list/asaas-loja-do-alagoano?cpfCnpj=85260731093
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar Webhook ####
GET {{base}}/webhook/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh


#### [ ] Recuparar senha ####
POST {{base}}/recover/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "maximizebot@gmail.com"
}

#### [ ] Alter Pass ####
POST {{base}}/alter/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "br.rafael@outlook.com",
    "code" : "AS56DA41SDA64D44AD",
    "pass" : "123456"
}

#### [ ] Bling ####
POST {{base}}/generate/token
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId" : "loja-do-alagoano1",
    "code" : "3d894267f2a7b3c248425eafe8c35fbcec9c537b"
}

#### [ ] Subscribe Bling ####
POST {{base}}/subscribe/bling
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId" : "loja-do-alagoano"
}

