### Variaveis ###
@base = https://api.paramour.com.br/v1
@storePublicId = bling-fdgwsdfgsgdfsgfdwre

#### [X] Login ####
POST {{base}}/login
Content-Type: application/json

{
    "email": "maximizebot@gmail.com",
    "pass": "Password@1"
}

#### [X] Listar Lojas ####
GET {{base}}/store/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar Informações da Lojas ####
GET {{base}}/store/info?publicId=a33c7aee-3738-4ab2-9947-c3e7764dd40d
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Cadastrar Lojas ####
POST {{base}}/store/register?debug=true
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId": "loja-do-alagoano",
    "name": "Loja do Alagoano",
    "email": "alagoano@gmail.com",
    "asaasApiKey": "0",
    "blingClientId": "1",
    "blingClientSecret": "2"
}

#### [X] Atualizar Lojas ####
POST {{base}}/store/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99",
    "externalId": "loja-do-alagoano1",
    "name": "Loja do Alagoano1",
    "email": "alagoano1@gmail.com",
    "asaasApiKey": "0",
    "blingClientId": "1",
    "blingClientSecret": "2"
}

#### [X] status Lojas ####
POST {{base}}/store/status
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99",
    "status": "INACTIVE"
}

#### [X] Deletar Lojas ####
POST {{base}}/store/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "9418cbfc-2dce-4db3-9bbf-86dc25f5ef99"
}

#### [X] Criar Usuarios ####
POST {{base}}/user/create
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "name": "Max",
    "email": "maximizebot@gmail.com",
    "pass": "Password@1",
    "phone": "123123"
}

#### [X] Listar Usuarios ####
GET {{base}}/user/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar informações do usuario ####
GET {{base}}/user/info?publicId=e58af946-0426-4629-831f-027b59a443d9
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Editar Usuarios ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "name": "admin_user_full2",
    "phone": "82 99621-0022",
    "status": "ACTIVE"
}

#### [X] Atualizar Senha de Usuarios ####
POST {{base}}/user/update/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "pass": "Password@12"
}

#### [X] Alterar dados do Usuario ####
POST {{base}}/user/update
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9",
    "name": "admin_user_edit",
    "phone": "82 99621-1554",
    "status": "ACTIVE"
}

#### [X] Deletar Usuarios ####
POST {{base}}/user/delete
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "publicId": "e58af946-0426-4629-831f-027b59a443d9"
}

#### [ ] Criar Webhook ####
POST {{base}}/webhook/create/bling-paramour-bahia
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

data={
  "retorno": {
    "pedidos": [
      {
        "pedido": {
          "desconto": "0,00",
          "observacoes": "",
          "observacaointerna": "",
          "data": "2024-09-12",
          "numero": "13837",
          "numeroOrdemCompra": "",
          "vendedor": "VENDA PARA FUNCIONÁRIOS",
          "valorfrete": "0.00",
          "outrasdespesas": "0.00",
          "totalprodutos": "27.45",
          "totalvenda": "27.45",
          "situacao": "Atendido",
          "dataSaida": "2024-09-12",
          "cliente": {
            "id": "15725544369",
            "nome": "LUCAS HENRIQUE DOMINGOS",
            "cnpj": "13511660696",
            "ie": "",
            "indIEDest": "9",
            "rg": "18769766",
            "endereco": "Rua Ipupiara",
            "numero": "53",
            "complemento": "APT",
            "cidade": "Salvador",
            "bairro": "Jardim das Margaridas",
            "cep": "41502385",
            "uf": "BA",
            "email": "lucaas.henrique2014@gmail.com",
            "celular": "(31) 97343-4734",
            "fone": "(31) 97343-4734"
          },
          "pagamento": {
            "categoria": "Vendas de mercadorias"
          },
          "transporte": {
            "tipo_frete": "R",
            "qtde_volumes": "0",
            "peso_bruto": "0.000"
          },
          "itens": [
            {
              "item": {
                "codigo": "1203126000",
                "descricao": "BRINCO FORMATO FOLHA COM DETALHES EM 3D",
                "quantidade": "1.0000",
                "valorunidade": "27.4500000000",
                "precocusto": "5.1700000000",
                "descontoItem": "0.00",
                "un": "PAR",
                "pesoBruto": "0.00000",
                "largura": "0",
                "altura": "0",
                "profundidade": "0",
                "descricaoDetalhada": "",
                "unidadeMedida": "cm",
                "gtin": ""
              }
            }
          ],
          "parcelas": [
            {
              "parcela": {
                "idLancamento": "21116306556",
                "valor": "27.45",
                "dataVencimento": "2024-09-13",
                "obs": "",
                "destino": "1",
                "forma_pagamento": {
                  "id": "6640310",
                  "descricao": "BOLETO ASAAS",
                  "codigoFiscal": "99"
                }
              }
            }
          ]
        }
      }
    ]
  }
}

#### [X] Listar Boletos ####
GET {{base}}/payment/list/asaas-paramour-bahia?cpfCnpj=13511660696
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

#### [X] Listar Webhook ####
GET {{base}}/webhook/list?page=1&itemsPerPage=100
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh


#### [ ] Recuparar senha ####
POST {{base}}/recover/pass?debug=true
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "maximizebot@gmail.com"
}

#### [ ] Alter Pass ####
POST {{base}}/alter/pass
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "email": "br.rafael@outlook.com",
    "code" : "AS56DA41SDA64D44AD",
    "pass" : "123456"
}

#### [ ] Bling ####
POST {{base}}/generate/token
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId" : "bling-paramour-bahia",
    "code" : "b6ea4294640cb66326d40d95e80a56f949f4e578"
}

#### [ ] Subscribe Bling ####
POST {{base}}/subscribe/bling
Content-Type: application/json
token: asdlkgnsdfgksnfdghpksdfgnh

{
    "externalId" : "loja-do-alagoano"
}

